modLoader="javafml"
loaderVersion="[55,)"
license="All Rights Reserved"

[[mods]]
modId="miscutility"
version="1.0.0"
displayName="misc utility mod"
authors="z4kkyy"
description="""
プレイヤーが死んだ際に、座標を表示するModです。
A mod that displays the coordinates when the player dies.
"""